### ISSUE TITLE
测试，dev

### ISSUE THREAD

**Issue by yqh708** [EwellFE/evell#2]
大神，你好，我想请教一下，您这个项目里面是不是没有在本地测试的，也没有见到在package.json配置有dev的代码？我也想写一个自己的ui库，但是现在思路很不清晰，恳请大神指点一下

**Comment by JohnsenZhou** [comment]
@yqh708 暂时没有本地测试，想写一个自己的ui库主要还是打包的配置和一些基础的框架组件知识，你可以参考这个项目
